[package]
name = "ch3"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { version = "22.1.0", default-features = false, features = [
    "wgsl",
    "dx12",
    "metal",
] }
winit = { version = "0.29", features = ["android-native-activity"] }
env_logger = "0.11"
pollster = "0.3"